insert into question(question) values('Which of these is not a primitive data type?');
insert into question(question) values('What is the syntax to create an object for class Animal?');
insert into question(question) values('In Java SE, what is: public static void main(String args[])?');
insert into question(question) values('What is an Array?');
insert into question(question) values('name a type of loop');

insert into Answer(Answer, correct, Answer_id) values('String', true, 1);
insert into Answer(Answer, correct, Answer_id) values('int', false, 1);
insert into Answer(Answer, correct, Answer_id) values('long', false, 1);
insert into Answer(Answer, correct, Answer_id) values('byte',false, 1);
insert into Answer(Answer, correct, Answer_id) values('Animal dog = new Animal();', true, 2);
insert into Answer(Answer, correct, Answer_id) values('new Animal;', false, 2);
insert into Answer(Answer, correct, Answer_id) values('Animal cat = new animal;', false, 2);
insert into Answer(Answer, correct, Answer_id) values('Animal = new Animal()', false, 2);
insert into Answer(Answer, correct, Answer_id) values('the method used to initialise a project', true, 3);
insert into Answer(Answer, correct, Answer_id) values('a method found in every class', false, 3);
insert into Answer(Answer, correct, Answer_id) values('a statement used outside the main class', false, 3);
insert into Answer(Answer, correct, Answer_id) values('A method not needed to run a project', false, 3);
insert into Answer(Answer, correct, Answer_id) values('a collection of common data types', true, 4);
insert into Answer(Answer, correct, Answer_id) values('A container storing multiple data types', false, 4);
insert into Answer(Answer, correct, Answer_id) values('used for holding a fixed number of values', false, 4);
insert into Answer(Answer, correct, Answer_id) values('A data type', false, 4);
insert into Answer(Answer, correct, Answer_id) values('for', true, 5);
insert into Answer(Answer, correct, Answer_id) values('if', false, 5);
insert into Answer(Answer, correct, Answer_id) values('switch case', false, 5);
insert into Answer(Answer, correct, Answer_id) values('super()', false, 5);
